version: '3.8'

services:
  duckduckgo-mcp:
    image: mcp/duckduckgo
    container_name: duckduckgo-mcp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duckduckgo.rule=Host(`duckduckgo-${RANDOM}.traefik.me`)"  # Traefik auto-generates random subdomains
      - "traefik.http.services.duckduckgo.loadbalancer.server.port=8080"  # Map port to the container's port
      - "traefik.http.routers.duckduckgo.entrypoints=websecure"  # Enable HTTPS entrypoint
      - "traefik.http.routers.duckduckgo.tls=true"  # Enable TLS (SSL)
      - "traefik.http.routers.duckduckgo.tls.certresolver=myresolver"  # Enable SSL via Let's Encrypt
    ports:
      - "8080:8080"  # Expose the port for the container (if required)
    environment:
      - MCP_SERVER=true
