version: '3.8'

services:
  duckduckgo-mcp:
    image: mcp/duckduckgo
    container_name: duckduckgo-mcp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duckduckgo.rule=Host(`duckduckgo-${RANDOM_STRING}.traefik.me`)"  # Using generated RANDOM_STRING
      - "traefik.http.services.duckduckgo.loadbalancer.server.port=8080"
      - "traefik.http.routers.duckduckgo.entrypoints=websecure"
      - "traefik.http.routers.duckduckgo.tls=true"
      - "traefik.http.routers.duckduckgo.tls.certresolver=myresolver"
    environment:
      - RANDOM_STRING=${RANDOM_STRING}  # Pass the random string as an environment variable
    ports:
      - "8080:8080"
