version: '3'
services:
  duckduckgo-mcp:
    image: mcp/duckduckgo
    container_name: duckduckgo-mcp
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MCP_SERVER=true
