version: '3.8'  # Update version

services:
  duckduckgo-mcp:
    image: mcp/duckduckgo
    container_name: duckduckgo-mcp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duckduckgo.rule=Host(`duckduckgo-${RANDOM}.traefik.me`)"
      - "traefik.http.services.duckduckgo.loadbalancer.server.port=8080"
    ports:
      - "8080:8080"  # Ensure port mapping
    environment:
      - MCP_SERVER=true
    # Command is not needed here; remove the line below
    # command: "run"  # This is likely causing the error
